[Service]
# Keep the notification daemon off the NVIDIA dGPU so Hybrid mode can idle it.
Environment=DRI_PRIME=0
Environment=__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json
Environment=VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.json
Environment=MESA_LOADER_DRIVER_OVERRIDE=iris
Environment=GSK_RENDERER=cairo
